version: '3.9'

services:
  web1:
    container_name: web1
    build: .
    ports:
      - 2222:22
  web2:
    container_name: web2
    build: .
    ports:
      - 2223:22
  web3:
    container_name: web3
    build: .
    ports:
      - 2224:22